services:
  epub-imgsplit:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: epub-imgsplit
    volumes:
      - ./in:/in
      - ./out:/out
    restart: "no"

  epub-imgsplit-images-only:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: epub-imgsplit-images-only
    command: ["--images-only"]
    volumes:
      - ./in:/in
      - ./out:/out
    restart: "no"

  epub-imgsplit-strict-filter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: epub-imgsplit-strict-filter
    command: ["--min-width", "3", "--min-height", "3"]
    volumes:
      - ./in:/in
      - ./out:/out
    restart: "no"