FROM mcr.microsoft.com/devcontainers/python:3.11-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \    libxml2 libxslt1.1 libxml2-dev libxslt1-dev \ && rm -rf /var/lib/apt/lists/*
